import type { DemoIconName } from './demo-icon';

const carbonMapping: Record<DemoIconName, string> = {
  'alert-circle': 'warning-alt',
  'archive': 'archive',
  'arrow-right': 'arrow-right',
  'bell': 'notification',
  'bot': 'bot',
  'chevron-down': 'chevron-down',
  'chevrons-up-down': 'chevron-sort',
  'circle-dot': 'radio-button-checked',
  'clock': 'time',
  'file-text': 'document',
  'filter': 'filter',
  'folder': 'folder',
  'inbox': 'email',
  'layers': 'layers',
  'link': 'link',
  'list': 'list',
  'more-horizontal': 'overflow-menu-horizontal',
  'plus': 'add',
  'search': 'search',
  'send': 'send',
  'square': 'square-outline',
  'star': 'star',
  'trash-2': 'trash-can',
  'x': 'x',
};

const circumMapping: Record<DemoIconName, string> = {
  'alert-circle': 'circle-alert',
  'archive': 'boxes',
  'arrow-right': 'turn-r-1',
  'bell': 'bell-on',
  'bot': 'microchip',
  'chevron-down': 'circle-chev-down',
  'chevrons-up-down': 'slider-vertical',
  'circle-dot': 'picker-empty',
  'clock': 'clock-1',
  'file-text': 'file-on',
  'filter': 'filter',
  'folder': 'folder-on',
  'inbox': 'inbox-in',
  'layers': 'boxes',
  'link': 'link',
  'list': 'view-list',
  'more-horizontal': 'menu-kebab',
  'plus': 'circle-plus',
  'search': 'search',
  'send': 'paperplane',
  'square': 'stop-1',
  'star': 'star',
  'trash-2': 'trash',
  'x': 'circle-remove',
};

const cuidaMapping: Record<DemoIconName, string> = {
  'alert-circle': 'alert-outline',
  'archive': 'box-outline',
  'arrow-right': 'arrow-right-outline',
  'bell': 'notification-bell-outline',
  'bot': 'sparks-outline',
  'chevron-down': 'caret-down-outline',
  'chevrons-up-down': 'unfold-vertical-outline',
  'circle-dot': 'single-select-outline',
  'clock': 'clock-outline',
  'file-text': 'document-text-outline',
  'filter': 'filter-outline',
  'folder': 'folder-outline',
  'inbox': 'mail-outline',
  'layers': 'layers-outline',
  'link': 'link-outline',
  'list': 'list-outline',
  'more-horizontal': 'more-horizontal-outline',
  'plus': 'plus-outline',
  'search': 'search-outline',
  'send': 'share-outline',
  'square': 'checkbox-unchecked-outlined',
  'star': 'star-outline',
  'trash-2': 'trash-outline',
  'x': 'x-outline',
};

const flowbiteMapping: Record<DemoIconName, string> = {
  'alert-circle': 'exclamation-circle-outline',
  'archive': 'archive-outline',
  'arrow-right': 'arrow-right-outline',
  'bell': 'bell-outline',
  'bot': 'brain-outline',
  'chevron-down': 'chevron-down-outline',
  'chevrons-up-down': 'chevron-sort-outline',
  'circle-dot': 'user-circle-outline',
  'clock': 'clock-outline',
  'file-text': 'file-lines-outline',
  'filter': 'filter-outline',
  'folder': 'folder-outline',
  'inbox': 'inbox-outline',
  'layers': 'layers-outline',
  'link': 'link-outline',
  'list': 'list-outline',
  'more-horizontal': 'dots-horizontal-outline',
  'plus': 'plus-outline',
  'search': 'search-outline',
  'send': 'paper-plane-outline',
  'square': 'stop-outline',
  'star': 'star-outline',
  'trash-2': 'trash-bin-outline',
  'x': 'close-outline',
};

const fluentMapping: Record<DemoIconName, string> = {
  'alert-circle': 'error-circle-24-regular',
  'archive': 'archive-24-regular',
  'arrow-right': 'arrow-right-24-regular',
  'bell': 'alert-24-regular',
  'bot': 'bot-24-regular',
  'chevron-down': 'chevron-down-24-regular',
  'chevrons-up-down': 'chevron-up-down-24-regular',
  'circle-dot': 'radio-button-24-regular',
  'clock': 'clock-24-regular',
  'file-text': 'document-text-24-regular',
  'filter': 'filter-24-regular',
  'folder': 'folder-24-regular',
  'inbox': 'mail-inbox-24-regular',
  'layers': 'layer-24-regular',
  'link': 'link-24-regular',
  'list': 'list-24-regular',
  'more-horizontal': 'more-horizontal-24-regular',
  'plus': 'add-24-regular',
  'search': 'search-24-regular',
  'send': 'send-24-regular',
  'square': 'square-24-regular',
  'star': 'star-24-regular',
  'trash-2': 'delete-24-regular',
  'x': 'dismiss-24-regular',
};

const gravityUiMapping: Record<DemoIconName, string> = {
  'alert-circle': 'circle-exclamation',
  'archive': 'archive',
  'arrow-right': 'arrow-right',
  'bell': 'bell',
  'bot': 'face-robot',
  'chevron-down': 'chevron-down',
  'chevrons-up-down': 'chevrons-expand-vertical',
  'circle-dot': 'circle',
  'clock': 'clock',
  'file-text': 'file-text',
  'filter': 'funnel',
  'folder': 'folder',
  'inbox': 'tray',
  'layers': 'layers',
  'link': 'link',
  'list': 'list-ul',
  'more-horizontal': 'ellipsis',
  'plus': 'plus',
  'search': 'magnifier',
  'send': 'paper-plane',
  'square': 'square',
  'star': 'star',
  'trash-2': 'trash-bin',
  'x': 'xmark',
};

const heroiconsMapping: Record<DemoIconName, string> = {
  'alert-circle': 'exclamation-circle',
  'archive': 'archive-box',
  'arrow-right': 'arrow-right',
  'bell': 'bell',
  'bot': 'cpu-chip',
  'chevron-down': 'chevron-down',
  'chevrons-up-down': 'chevron-up-down',
  'circle-dot': 'viewfinder-dot', 
  'clock': 'clock',
  'file-text': 'document-text',
  'filter': 'funnel',
  'folder': 'folder',
  'inbox': 'inbox',
  'layers': 'square-2-stack',
  'link': 'link',
  'list': 'list-bullet',
  'more-horizontal': 'ellipsis-horizontal',
  'plus': 'plus',
  'search': 'magnifying-glass',
  'send': 'paper-airplane',
  'square': 'square-2-stack',
  'star': 'star',
  'trash-2': 'trash',
  'x': 'x-mark',
};

const hugeiconsMapping: Record<DemoIconName, string> = {
  'alert-circle': 'alert-circle',
  'archive': 'archive',
  'arrow-right': 'arrow-right-01',
  'bell': 'notification-01',
  'bot': 'bot',
  'chevron-down': 'chevron-down',
  'chevrons-up-down': 'chevrons-down-up',
  'circle-dot': 'circle',
  'clock': 'clock-01',
  'file-text': 'file-01',
  'filter': 'filter',
  'folder': 'folder-01',
  'inbox': 'inbox',
  'layers': 'layers-01',
  'link': 'link-01',
  'list': 'menu-01',
  'more-horizontal': 'more-horizontal',
  'plus': 'plus-sign',
  'search': 'search-01',
  'send': 'sent',
  'square': 'square',
  'star': 'star',
  'trash-2': 'delete-02',
  'x': 'cancel-01',
};

const iconParkMapping: Record<DemoIconName, string> = {
  'alert-circle': 'attention',
  'archive': 'box',
  'arrow-right': 'arrow-right',
  'bell': 'remind',
  'bot': 'robot',
  'chevron-down': 'down',
  'chevrons-up-down': 'up-and-down',
  'circle-dot': 'dot',
  'clock': 'clock-tower',
  'file-text': 'file-text',
  'filter': 'filter',
  'folder': 'folder',
  'inbox': 'inbox',
  'layers': 'layers',
  'link': 'link',
  'list': 'list',
  'more-horizontal': 'more',
  'plus': 'plus',
  'search': 'search',
  'send': 'send',
  'square': 'square',
  'star': 'star',
  'trash-2': 'delete',
  'x': 'close',
};

const iconamoonMapping: Record<DemoIconName, string> = {
  'alert-circle': 'attention-circle',
  'archive': 'box',
  'arrow-right': 'arrow-right-1',
  'bell': 'notification',
  'bot': 'profile',
  'chevron-down': 'arrow-down-1',
  'chevrons-up-down': 'swap',
  'circle-dot': 'profile-circle',
  'clock': 'clock',
  'file-text': 'file-document',
  'filter': 'funnel',
  'folder': 'folder',
  'inbox': 'email',
  'layers': 'frame',
  'link': 'link',
  'list': 'playlist',
  'more-horizontal': 'menu-kebab-horizontal',
  'plus': 'sign-plus',
  'search': 'search',
  'send': 'send',
  'square': 'frame',
  'star': 'star',
  'trash-2': 'trash',
  'x': 'close',
};

const iconoirMapping: Record<DemoIconName, string> = {
  'alert-circle': 'warning-circle',
  'archive': 'archive',
  'arrow-right': 'arrow-right',
  'bell': 'bell',
  'bot': 'user',
  'chevron-down': 'nav-arrow-down',
  'chevrons-up-down': 'sort',
  'circle-dot': 'circle',
  'clock': 'clock',
  'file-text': 'page',
  'filter': 'filter',
  'folder': 'folder',
  'inbox': 'mail',
  'layers': 'frame',
  'link': 'link',
  'list': 'list',
  'more-horizontal': 'more-horiz',
  'plus': 'plus',
  'search': 'search',
  'send': 'send',
  'square': 'square',
  'star': 'star',
  'trash-2': 'trash',
  'x': 'xmark',
};

const letsIconsMapping: Record<DemoIconName, string> = {
  'alert-circle': 'info',
  'archive': 'arhive',
  'arrow-right': 'arrow-right',
  'bell': 'bell',
  'bot': 'user',
  'chevron-down': 'down',
  'chevrons-up-down': 'vertical-switch',
  'circle-dot': 'user-cicrle',
  'clock': 'clock',
  'file-text': 'paper',
  'filter': 'filter',
  'folder': 'folder',
  'inbox': 'e-mail',
  'layers': 'layers',
  'link': 'link',
  'list': 'order',
  'more-horizontal': 'meatballs-menu',
  'plus': 'add',
  'search': 'search',
  'send': 'send',
  'square': 'frame',
  'star': 'star',
  'trash-2': 'trash',
  'x': 'cancel',
};

const lineMdMapping: Record<DemoIconName, string> = {
  'alert-circle': 'alert-circle',
  'archive': 'document',
  'arrow-right': 'arrow-right',
  'bell': 'bell',
  'bot': 'computer',
  'chevron-down': 'chevron-down',
  'chevrons-up-down': 'double-arrow-vertical',
  'circle-dot': 'circle',
  'clock': 'gauge',
  'file-text': 'document-document',
  'filter': 'filter',
  'folder': 'folder',
  'inbox': 'email',
  'layers': 'square',
  'link': 'link',
  'list': 'list',
  'more-horizontal': 'menu',
  'plus': 'plus',
  'search': 'search',
  'send': 'send',
  'square': 'square',
  'star': 'star',
  'trash-2': 'trash',
  'x': 'close',
};

const lsiconMapping: Record<DemoIconName, string> = {
  'alert-circle': 'circle-warning-outline',
  'archive': 'archive-outline',
  'arrow-right': 'arrow-right-outline',
  'bell': 'remind-outline',
  'bot': 'computer-outline',
  'chevron-down': 'down-outline',
  'chevrons-up-down': 'double-arrow-up-outline',
  'circle-dot': 'radio-selected-outline',
  'clock': 'oclock-outline',
  'file-text': 'file-txt-outline',
  'filter': 'filter-outline',
  'folder': 'folder-outline',
  'inbox': 'inbox-outline',
  'layers': 'coverage-outline',
  'link': 'link-outline',
  'list': 'list-outline',
  'more-horizontal': 'more-outline',
  'plus': 'add-one-outline',
  'search': 'search-outline',
  'send': 'send-outline',
  'square': 'checkbox-outline',
  'star': 'star-outline',
  'trash-2': 'delete-outline',
  'x': 'close-small-outline',
};

const lucideMapping: Record<DemoIconName, string> = {
  'alert-circle': 'alert-circle',
  'archive': 'archive',
  'arrow-right': 'arrow-right',
  'bell': 'bell',
  'bot': 'bot',
  'chevron-down': 'chevron-down',
  'chevrons-up-down': 'chevrons-up-down',
  'circle-dot': 'circle-dot',
  'clock': 'clock',
  'file-text': 'file-text',
  'filter': 'filter',
  'folder': 'folder',
  'inbox': 'inbox',
  'layers': 'layers',
  'link': 'link',
  'list': 'list',
  'more-horizontal': 'more-horizontal',
  'plus': 'plus',
  'search': 'search',
  'send': 'send',
  'square': 'square',
  'star': 'star',
  'trash-2': 'trash-2',
  'x': 'x',
};

const mageMapping: Record<DemoIconName, string> = {
  'alert-circle': 'exclamation-circle',
  'archive': 'archive',
  'arrow-right': 'arrow-right',
  'bell': 'notification-bell',
  'bot': 'robot',
  'chevron-down': 'chevron-down',
  'chevrons-up-down': 'double-arrow-up',
  'circle-dot': 'focus',
  'clock': 'clock',
  'file-text': 'note-text',
  'filter': 'filter',
  'folder': 'folder',
  'inbox': 'inbox',
  'layers': 'stack',
  'link': 'link',
  'list': 'checklist',
  'more-horizontal': 'dots-horizontal',
  'plus': 'plus',
  'search': 'search',
  'send': 'upload',
  'square': 'select-box',
  'star': 'star',
  'trash-2': 'trash-2',
  'x': 'x',
};

const materialSymbolsMapping: Record<DemoIconName, string> = {
  'alert-circle': 'error-outline',
  'archive': 'archive-outline',
  'arrow-right': 'arrow-right',
  'bell': 'notifications-outline',
  'bot': 'smart-toy-outline',
  'chevron-down': 'expand-more',
  'chevrons-up-down': 'unfold-more',
  'circle-dot': 'radio-button-checked',
  'clock': 'schedule',
  'file-text': 'description-outline',
  'filter': 'filter-alt-outline',
  'folder': 'folder-outline',
  'inbox': 'inbox-outline',
  'layers': 'layers-outline',
  'link': 'link',
  'list': 'list',
  'more-horizontal': 'more-horiz',
  'plus': 'add',
  'search': 'search',
  'send': 'send-outline',
  'square': 'square-outline',
  'star': 'star-outline',
  'trash-2': 'delete-outline',
  'x': 'close',
};

const mingcuteMapping: Record<DemoIconName, string> = {
  'alert-circle': 'alert-line',
  'archive': 'archive-line',
  'arrow-right': 'arrow-right-line',
  'bell': 'notification-line',
  'bot': 'robot-line',
  'chevron-down': 'down-line',
  'chevrons-up-down': 'selector-vertical-line',
  'circle-dot': 'dot-circle-line',
  'clock': 'clock-line',
  'file-text': 'file-line',
  'filter': 'filter-line',
  'folder': 'folder-line',
  'inbox': 'inbox-line',
  'layers': 'layers-line',
  'link': 'link-line',
  'list': 'list-check-line',
  'more-horizontal': 'more-1-line',
  'plus': 'add-line',
  'search': 'search-line',
  'send': 'send-line',
  'square': 'square-line',
  'star': 'star-line',
  'trash-2': 'delete-line',
  'x': 'close-line',
};

const mynauiMapping: Record<DemoIconName, string> = {
  'alert-circle': 'danger-circle',
  'archive': 'archive',
  'arrow-right': 'arrow-right',
  'bell': 'bell',
  'bot': 'bot',
  'chevron-down': 'chevron-down',
  'chevrons-up-down': 'chevrons-up-down',
  'circle-dot': 'circle-dashed',
  'clock': 'clock-circle',
  'file-text': 'file-text',
  'filter': 'filter',
  'folder': 'folder',
  'inbox': 'inbox',
  'layers': 'layers-three',
  'link': 'link',
  'list': 'list',
  'more-horizontal': 'dots',
  'plus': 'plus',
  'search': 'search',
  'send': 'send',
  'square': 'square',
  'star': 'star',
  'trash-2': 'trash-two',
  'x': 'x',
};

const phMapping: Record<DemoIconName, string> = {
  'alert-circle': 'warning-circle',
  'archive': 'archive',
  'arrow-right': 'arrow-right',
  'bell': 'bell',
  'bot': 'robot',
  'chevron-down': 'caret-down',
  'chevrons-up-down': 'arrows-down-up',
  'circle-dot': 'circle',
  'clock': 'clock',
  'file-text': 'file-text',
  'filter': 'funnel',
  'folder': 'folder',
  'inbox': 'tray',
  'layers': 'stack',
  'link': 'link',
  'list': 'list',
  'more-horizontal': 'dots-three',
  'plus': 'plus',
  'search': 'magnifying-glass',
  'send': 'paper-plane',
  'square': 'square',
  'star': 'star',
  'trash-2': 'trash',
  'x': 'x',
};

const proiconsMapping: Record<DemoIconName, string> = {
  'alert-circle': 'alert-circle',
  'archive': 'archive',
  'arrow-right': 'arrow-right',
  'bell': 'bell',
  'bot': 'sparkle',
  'chevron-down': 'chevron-down',
  'chevrons-up-down': 'arrow-up-down',
  'circle-dot': 'dot-circle',
  'clock': 'clock',
  'file-text': 'file-text',
  'filter': 'filter',
  'folder': 'folder',
  'inbox': 'box',
  'layers': 'layers',
  'link': 'link',
  'list': 'bullet-list',
  'more-horizontal': 'more',
  'plus': 'add',
  'search': 'search',
  'send': 'send',
  'square': 'square',
  'star': 'star',
  'trash-2': 'delete',
  'x': 'cancel',
};

const radixIconsMapping: Record<DemoIconName, string> = {
  'alert-circle': 'exclamation-circled',
  'archive': 'archive',
  'arrow-right': 'arrow-right',
  'bell': 'bell',
  'bot': 'codesandbox-logo',
  'chevron-down': 'chevron-down',
  'chevrons-up-down': 'double-arrow-up',
  'circle-dot': 'dot-filled',
  'clock': 'clock',
  'file-text': 'file-text',
  'filter': 'filter',
  'folder': 'folder',
  'inbox': 'reader',
  'layers': 'layers',
  'link': 'link-1',
  'list': 'list-bullet',
  'more-horizontal': 'dots-horizontal',
  'plus': 'plus',
  'search': 'magnifying-glass',
  'send': 'paper-plane',
  'square': 'square',
  'star': 'star',
  'trash-2': 'trash',
  'x': 'cross-1',
};

const riMapping: Record<DemoIconName, string> = {
  'alert-circle': 'alert-line',
  'archive': 'archive-line',
  'arrow-right': 'arrow-right-line',
  'bell': 'bell-line',
  'bot': 'robot-line',
  'chevron-down': 'arrow-down-s-line',
  'chevrons-up-down': 'arrow-up-down-line',
  'circle-dot': 'checkbox-blank-circle-line',
  'clock': 'time-line',
  'file-text': 'file-text-line',
  'filter': 'filter-line',
  'folder': 'folder-line',
  'inbox': 'inbox-line',
  'layers': 'stack-line',
  'link': 'link',
  'list': 'list-unordered',
  'more-horizontal': 'more-line',
  'plus': 'add-line',
  'search': 'search-line',
  'send': 'send-plane-line',
  'square': 'square-line',
  'star': 'star-line',
  'trash-2': 'delete-bin-line',
  'x': 'close-line',
};

const solarMapping: Record<DemoIconName, string> = {
  'alert-circle': 'danger-circle-linear',
  'archive': 'archive-linear',
  'arrow-right': 'arrow-right-linear',
  'bell': 'bell-linear',
  'bot': 'smart-vacuum-cleaner-linear',
  'chevron-down': 'alt-arrow-down-linear',
  'chevrons-up-down': 'sort-vertical-linear',
  'circle-dot': 'record-circle-linear',
  'clock': 'clock-circle-linear',
  'file-text': 'file-text-linear',
  'filter': 'filter-linear',
  'folder': 'folder-linear',
  'inbox': 'inbox-linear',
  'layers': 'layers-linear',
  'link': 'link-linear',
  'list': 'list-linear',
  'more-horizontal': 'menu-dots-linear',
  'plus': 'add-circle-linear',
  'search': 'magnifier-linear',
  'send': 'plain-linear',
  'square': 'square-academic-cap-2-linear',
  'star': 'star-linear',
  'trash-2': 'trash-bin-2-linear',
  'x': 'close-circle-linear',
};

const stashMapping: Record<DemoIconName, string> = {
  'alert-circle': 'exclamation-circle',
  'archive': 'pack',
  'arrow-right': 'arrow-right',
  'bell': 'bell',
  'bot': 'racket',
  'chevron-down': 'angle-down',
  'chevrons-up-down': 'arrows-switch',
  'circle-dot': 'circle-dot',
  'clock': 'clock',
  'file-text': 'article',
  'filter': 'filter',
  'folder': 'folder',
  'inbox': 'inbox',
  'layers': 'pack',
  'link': 'link',
  'list': 'list-ul',
  'more-horizontal': 'ellipsis-h',
  'plus': 'plus',
  'search': 'search',
  'send': 'paperplane',
  'square': 'square',
  'star': 'star',
  'trash-2': 'trash-can',
  'x': 'times',
};

const streamlineMapping: Record<DemoIconName, string> = {
  'alert-circle': 'interface-alert-warning-circle-warning-alert-frame-exclamation-caution-circle',
  'archive': 'interface-content-archive-box-content-banker-archive-file',
  'arrow-right': 'interface-arrows-button-right-arrow-right-keyboard',
  'bell': 'interface-alert-alarm-bell-1-notification-vibrate-ring-sound-alarm-alert-bell-noise',
  'bot': 'computer-robot-cyborg-artificial-robotics-robot-intelligence-machine-technology-android',
  'chevron-down': 'interface-arrows-button-down-arrow-down-keyboard',
  'chevrons-up-down': 'interface-arrows-horizontal-up-down-expand-resize-bigger-vertical-smaller-size-arrow-arrows-big',
  'circle-dot': 'interface-geometric-circle-geometric-circle-round-design-shape-shapes',
  'clock': 'interface-time-clock-circle-clock-loading-measure-time-circle',
  'file-text': 'interface-file-text-text-common-file',
  'filter': 'interface-text-formatting-filter-1-funnel-filter-round-oil',
  'folder': 'interface-folder-empty-folder',
  'inbox': 'mail-inbox-email-outbox-drawer-empty-open-inbox',
  'layers': 'layers-1',
  'link': 'interface-link-create-hyperlink-link-make-unlink',
  'list': 'interface-text-formatting-list-bullets-points-bullet-unordered-list-lists-bullets',
  'more-horizontal': 'interface-setting-menu-horizontal-navigation-dots-three-circle-button-horizontal-menu',
  'plus': 'interface-add-1-expand-cross-buttons-button-more-remove-plus-add',
  'search': 'interface-search-glass-search-magnifying',
  'send': 'mail-send-email-send-email-paper-airplane',
  'square': 'interface-geometric-square-square-geometric-design-shape-shapes',
  'star': 'interface-favorite-star-reward-rating-rate-social-star-media-favorite-like-stars',
  'trash-2': 'interface-delete-bin-2-remove-delete-empty-bin-trash-garbage',
  'x': 'interface-delete-2-remove-bold-add-button-buttons-delete',
};

const systemUiconsMapping: Record<DemoIconName, string> = {
  'alert-circle': 'warning-circle',
  'archive': 'archive',
  'arrow-right': 'arrow-right',
  'bell': 'bell',
  'bot': 'cpu',
  'chevron-down': 'chevron-down',
  'chevrons-up-down': 'sort',
  'circle-dot': 'radio-on',
  'clock': 'clock',
  'file-text': 'document',
  'filter': 'filter',
  'folder': 'folder-closed',
  'inbox': 'inbox',
  'layers': 'document-stack',
  'link': 'link',
  'list': 'list',
  'more-horizontal': 'menu-horizontal',
  'plus': 'plus',
  'search': 'search',
  'send': 'paper-plane',
  'square': 'box',
  'star': 'star',
  'trash-2': 'trash-alt',
  'x': 'cross',
};

const tablerMapping: Record<DemoIconName, string> = {
  'alert-circle': 'alert-circle',
  'archive': 'archive',
  'arrow-right': 'arrow-right',
  'bell': 'bell',
  'bot': 'robot',
  'chevron-down': 'chevron-down',
  'chevrons-up-down': 'arrows-sort',
  'circle-dot': 'circle-dot',
  'clock': 'clock',
  'file-text': 'file-text',
  'filter': 'filter',
  'folder': 'folder',
  'inbox': 'inbox',
  'layers': 'layers',
  'link': 'link',
  'list': 'list',
  'more-horizontal': 'dots',
  'plus': 'plus',
  'search': 'search',
  'send': 'send',
  'square': 'square',
  'star': 'star',
  'trash-2': 'trash',
  'x': 'x',
};

const tdesignMapping: Record<DemoIconName, string> = {
  'alert-circle': 'error-circle',
  'archive': 'folder',
  'arrow-right': 'arrow-right',
  'bell': 'notification',
  'bot': 'robot',
  'chevron-down': 'chevron-down',
  'chevrons-up-down': 'order-ascending',
  'circle-dot': 'radio-1',
  'clock': 'time',
  'file-text': 'file',
  'filter': 'filter',
  'folder': 'folder',
  'inbox': 'outbox',
  'layers': 'layers',
  'link': 'link',
  'list': 'list',
  'more-horizontal': 'ellipsis',
  'plus': 'plus',
  'search': 'search',
  'send': 'send',
  'square': 'rectangle',
  'star': 'star',
  'trash-2': 'delete',
  'x': 'close',
};

const teenyiconsMapping: Record<DemoIconName, string> = {
  'alert-circle': 'exclamation-circle-outline',
  'archive': 'archive-outline',
  'arrow-right': 'arrow-right-outline',
  'bell': 'bell-outline',
  'bot': 'robot-outline',
  'chevron-down': 'down-outline',
  'chevrons-up-down': 'adjust-vertical-outline',
  'circle-dot': 'target-outline',
  'clock': 'clock-outline',
  'file-text': 'text-document-outline',
  'filter': 'filter-outline',
  'folder': 'folder-outline',
  'inbox': 'inbox-outline',
  'layers': 'layers-outline',
  'link': 'link-outline',
  'list': 'list-unordered-outline',
  'more-horizontal': 'more-horizontal-outline',
  'plus': 'add-outline',
  'search': 'search-outline',
  'send': 'send-outline',
  'square': 'square-outline',
  'star': 'star-outline',
  'trash-2': 'bin-outline',
  'x': 'x-outline',
};

export const iconMappings: Record<string, Record<DemoIconName, string>> = {
  'carbon': carbonMapping,
  'circum': circumMapping,
  'cuida': cuidaMapping,
  'flowbite': flowbiteMapping,
  'fluent': fluentMapping,
  'gravity-ui': gravityUiMapping,
  'heroicons': heroiconsMapping,
  'hugeicons': hugeiconsMapping,
  'icon-park': iconParkMapping,
  'iconamoon': iconamoonMapping,
  'iconoir': iconoirMapping,
  'lets-icons': letsIconsMapping,
  'line-md': lineMdMapping,
  'lsicon': lsiconMapping,
  'lucide': lucideMapping,
  'mage': mageMapping,
  'material-symbols': materialSymbolsMapping,
  'mingcute': mingcuteMapping,
  'mynaui': mynauiMapping,
  'ph': phMapping,
  'proicons': proiconsMapping,
  'radix-icons': radixIconsMapping,
  'ri': riMapping,
  'solar': solarMapping,
  'stash': stashMapping,
  'streamline': streamlineMapping,
  'system-uicons': systemUiconsMapping,
  'tabler': tablerMapping,
  'tdesign': tdesignMapping,
  'teenyicons': teenyiconsMapping,
};

export type IconLibraryKey = keyof typeof iconMappings;
