export const colors = {
  warn: 'rgb(var(--warn))',
  error: 'rgb(var(--error))',
  success: 'rgb(var(--success))',
  scarab: 'rgb(var(--scarab))',
  mint: 'rgb(var(--mint))',
  sand: 'rgb(var(--sand))',
  neutron: 'rgb(var(--neutron))',
  prune: 'rgb(var(--prune))',
  accent: 'rgb(var(--accent))',
  paper: 'rgb(var(--paper))',
  parchment: 'rgb(var(--parchment))',
  papyrus: 'rgb(var(--papyrus))',
  line: 'rgb(var(--line))',
  ink: 'rgb(var(--ink))',
  lead: 'rgb(var(--lead))',
  graphite: 'rgb(var(--graphite))',
  stare: 'rgb(var(--stare))',
  scan: 'rgb(var(--scan))',
  gaze: 'rgb(var(--gaze))',
  'forced-a': 'rgb(var(--forced-a))',
  'forced-b': 'rgb(var(--forced-b))',
} as const;
